### ISSUE TITLE
Typing mistake

### ISSUE THREAD

**Issue by vitish** [playbook-ui/playbook-ios#16]
## Checklist

- [x] This is not a Apple's bug.  
- [x] Reviewed the README and documents.  
- [x] Searched existing issues for ensure not duplicated.  

## Description (Include Screenshots)
In the playbook README and API Document, in the second paragraph where the sentence starts with 'Components built using...'; instead of writing 'can generates' write 'generate'. 

## Steps to Reproduce

1. Go to https://github.com/playbook-ui/playbook-ios or https://playbook-ui.github.io/playbook-ios/. 
2. Go to the README section at https://github.com/playbook-ui/playbook-ios 
                                                 and
    Read the **Introduction** section at https://playbook-ui.github.io/playbook-ios/.

3. Read the **README** and/or **Introduction** section. 
4. Read the first line of the second paragraph. 

## Environments

- Library version:

- Swift version:

- iOS version:

- Xcode version:

- Devices/Simulators:

- Package manager version:

**Comment by ra1028** [comment]
@vitish 
Thanks for some issue reports.
But, in the next time, please gather into one all little issues on the same topic.
