### ISSUE TITLE
Incorrect article

### ISSUE THREAD

**Issue by vitish** [playbook-ui/playbook-ios#19]
## Checklist

- [x] This is not a Apple's bug.  
- [x] Reviewed the README and documents.  
- [x] Searched existing issues for ensure not duplicated.  

## Description (Include Screenshots)
At the https://playbook-ui.github.io/playbook-ios/Playbook.html, in **ScenarioStore**, in the **Parameters** section, in the first bullet point, instead of an write a.

## Steps to Reproduce

1. Go to https://playbook-ui.github.io/playbook-ios/.
2. Click the **ScenarioStore**
3. In the **Parameters** section, in the first bullet point, instead of _an_ write _a_.

## Environments

- Library version:

- Swift version:

- iOS version:

- Xcode version:

- Devices/Simulators:

- Package manager version:

**Comment by akashgujju** [comment]
Can I work on this?

**Comment by vitish** [comment]
Sure, you can.
