### ISSUE TITLE
Mention the purpose of the document

### ISSUE THREAD

**Issue by vitish** [playbook-ui/playbook-ios#23]
## Checklist

- [x] This is not a Apple's bug.  
- [x] Reviewed the README and documents.  
- [x] Searched existing issues for ensure not duplicated.  

## Description (Include Screenshots)
Mention the purpose of the document located at https://playbook-ui.github.io/playbook-ios/. The document lists APIS. However, it nowhere mentions that it is an API document. Please provide an appropriate title/heading.  

## Steps to Reproduce

1. Go to https://playbook-ui.github.io/playbook-ios/. 
2. In the menu on the left, read headings. 
3. Review if you can read API document anywhere.

## Environments

- Library version:

- Swift version:

- iOS version:

- Xcode version:

- Devices/Simulators:

- Package manager version:

**Comment by ra1028** [comment]
It is self-evident that it's a API document by looking at it.
In addition, README has a link for it as an API document.

**Comment by vitish** [comment]
I am aware of that. However, in terms of documentation, you must mention the obvious because it is not clarified within the document. I do not have to go somewhere else to see which document is that.
