### ISSUE TITLE
Scenario names containing the path separator (`/`) causes test failure

### ISSUE THREAD

**Issue by akkyie** [playbook-ui/playbook-ios#38]
## Checklist

- [x] This is not a Apple's bug.  
- [x] Reviewed the README and documents.  
- [x] Searched existing issues for ensure not duplicated.  

## Description (Include Screenshots)

Hi, I found that scenario names containing the path separator (`/`) can be problematic.

When it's used in the name of a group of scenarios, it's recognized literally as a path separator and makes additional directory structure. I couldn't figure out whether this is an intended behavior or not.

<img width="50%" alt="Screen Shot 2020-11-05 at 14 31 56" src="https://user-images.githubusercontent.com/1528813/98202150-b9df0400-1f74-11eb-9891-7b0419438f16.png">

When it's in a scenario name, it causes the test to fail with an error "No such file or directory." I guess it's a bit confusing, and would be best to be avoided.

<img width="50%" alt="image" src="https://user-images.githubusercontent.com/1528813/98202214-e004a400-1f74-11eb-8883-22f6c76403eb.png">

A few possible ways to improve it I have in my mind:
- Encode the entire name in a URL safe way such as `addingPercentEncoding`
- Replace only `/` with another (say, `_`)
- Throw an error with an improved message like "You cannot use `/` in a scenario name"

Encoding the whole is indeed the most safe way, but will make the report generated by [reg-suit](https://github.com/reg-viz/reg-suit) ugly. What do you think?

Last but not least, thank you for sharing and maintaining this great project!

## Steps to Reproduce

Contain `/` in names; see screenshots above.

## Reproducible Demo Project

Reproducible with the example project.

## Environments

- Library version: Checked with the example in master (c8c14d7b066c)
- Swift version: Apple Swift version 5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)
- iOS version: 14
- Xcode version: Version 12.1 (12A7403)
- Devices/Simulators: iPhone 12
- Package manager version: N/A

**Comment by ra1028** [comment]
@akkyie 
Thanks for your reporting and clarification. You caught a good point.
In that case, I prefer the first way that you suggested over the other ways, cuz it seems the safest and reasonable case as you mentioned. However, the percent-encoding hurts a file name of scenarios, right?
So, I'd suggest the way that replacing non-alphabetical characters except for a space character ` ` with `_`.
How do you think about it?

**Comment by ra1028** [comment]
After a little bit more thought, I think the chars that need to be replaced are `/` and `.`. Does it make sense?

**Comment by akkyie** [comment]
Yes, my personal preference is replacing/encoding only specific characters which lead problems, because we sometimes use non-alphabetic language for names (yes, Japanese) and rather want them to be shown as is.

Replacing only `/` and `.` sounds good to me. I think replacing whitespaces too can be a reasonable precautions because they may be not handled properly by some other programs (hasn't yet been a problem for us though.)

**Comment by ra1028** [comment]
@akkyie 
Sorry, I've just edited my comment before you submit the comment lol

Makes sense and I totally agree with your opinion.
I'll fix that problem by replacing `:`, `/`, ` `(white space), `.`, `\n`, and some other characters that are expected to cause problems. Thanks for your suggestion.

**Comment by akkyie** [comment]
No problem! These replacement targets sounds complete.
Really appreciate your quick response 🙏

**Comment by ra1028** [comment]
@akkyie 
I've merged a PR for fixing that. I'm gonna publish a new version after I fixed another issue on PlaybookUI.
Thanks!
